//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingByTesting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainingByTesting.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        internal static string Armenia {
            get {
                return ResourceManager.GetString("Armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarus.
        /// </summary>
        internal static string Belarus {
            get {
                return ResourceManager.GetString("Belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gomel.
        /// </summary>
        internal static string Gomel {
            get {
                return ResourceManager.GetString("Gomel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krakow.
        /// </summary>
        internal static string Krakow {
            get {
                return ResourceManager.GetString("Krakow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minsk.
        /// </summary>
        internal static string Minsk {
            get {
                return ResourceManager.GetString("Minsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOG.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trainings are available..
        /// </summary>
        internal static string NoTrainings {
            get {
                return ResourceManager.GetString("NoTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        internal static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        internal static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryazan.
        /// </summary>
        internal static string Ryazan {
            get {
                return ResourceManager.GetString("Ryazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tashkent.
        /// </summary>
        internal static string Tashkent {
            get {
                return ResourceManager.GetString("Tashkent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAINING LIST.
        /// </summary>
        internal static string TrainingList {
            get {
                return ResourceManager.GetString("TrainingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbekistan.
        /// </summary>
        internal static string Uzbekistan {
            get {
                return ResourceManager.GetString("Uzbekistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerevan.
        /// </summary>
        internal static string Yerevan {
            get {
                return ResourceManager.GetString("Yerevan", resourceCulture);
            }
        }
    }
}
